[package]
name = "iced-cn"
description = "A port of shadcn/ui for `iced`"
keywords = ["iced", "theme"]
readme = "README.md"
license = "MIT"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
iced_widget = "0.13.1"

[features]
default = []